//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genius2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Genius2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/table&gt;
        ///
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string BomFooter {
            get {
                return ResourceManager.GetString("BomFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;style&gt;
        ///table {
        ///  font-family: arial, sans-serif;
        ///  border-collapse: collapse;
        ///  width: 100%;
        ///}
        ///
        ///td, th {
        ///  border: 1px solid #dddddd;
        ///  text-align: left;
        ///  padding: 8px;
        ///}
        ///
        ///tr:nth-child(even) {
        ///  background-color: #dddddd;
        ///}
        ///&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///$TOTAL_TABLE
        ///&lt;h2&gt;Bill of material&lt;/h2&gt;
        ///
        ///&lt;table&gt;
        ///  &lt;tr&gt;
        ///  &lt;th&gt;SERNR&lt;/th&gt;
        ///  &lt;th&gt;VBELN &lt;/th&gt;
        ///  &lt;th&gt;VBPOS &lt;/th&gt;
        ///  &lt;th&gt;POSNR&lt;/th&gt;
        ///  &lt;th&gt;POSTP&lt;/th&gt;
        ///  &lt;th&gt;STLKN&lt;/th&gt;
        ///  &lt;th&gt;IDNRK&lt;/th&gt;
        ///  &lt;th&gt;POTX1&lt;/th&gt;
        ///  &lt;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BomHeader {
            get {
                return ResourceManager.GetString("BomHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/table&gt;.
        /// </summary>
        internal static string licenseoverviewFooter {
            get {
                return ResourceManager.GetString("licenseoverviewFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;style&gt;
        ///table {
        ///  font-family: arial, sans-serif;
        ///  border-collapse: collapse;
        ///  width: 100%;
        ///}
        ///
        ///td, th {
        ///  border: 1px solid #dddddd;
        ///  text-align: left;
        ///  padding: 8px;
        ///}
        ///
        ///tr:nth-child(even) {
        ///  background-color: #dddddd;
        ///}
        ///&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///&lt;h2&gt;Map license overview, machines with Infoware maps&lt;/h2&gt;
        ///#BEFORE_TABLE
        ///&lt;table&gt;
        ///  &lt;tr&gt;
        ///    &lt;th&gt;LSO&lt;/th&gt;
        ///    &lt;th&gt;Customer&lt;/th&gt;
        ///    &lt;th&gt;Machine&lt;/th&gt;
        ///    &lt;th&gt;Map version&lt;/th&gt;
        ///    &lt;th&gt;Map license&lt;/th&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string licenseoverviewHeader {
            get {
                return ResourceManager.GetString("licenseoverviewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /config=@xmlpath /CP_dir=\\NLHLNTF1\Data\F_data\ASCS\Software\ControlPanel /JC_dir=\\NLHLNTF1\Data\F_data\ASCS\Software\JobController  /override_sets=2,3,4,5,6,7,8,9,10 /outputfile=@pst3file /nogui.
        /// </summary>
        internal static string pst3builder {
            get {
                return ResourceManager.GetString("pst3builder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/table&gt;.
        /// </summary>
        internal static string totalTableFooter {
            get {
                return ResourceManager.GetString("totalTableFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table&gt;
        ///  &lt;tr&gt;
        ///    &lt;th&gt;Article&lt;/th&gt;
        ///    &lt;th&gt;Map version&lt;/th&gt;
        ///    &lt;th&gt;Amount&lt;/th&gt;
        ///  &lt;/tr&gt;.
        /// </summary>
        internal static string totalTableHeader {
            get {
                return ResourceManager.GetString("totalTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///  &lt;title&gt;XML Tree Viewer&lt;/title&gt;
        ///  &lt;link rel=&quot;stylesheet&quot; href=&quot;https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/themes/default/style.min.css&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///  &lt;div id=&quot;xmlTree&quot;&gt;&lt;/div&gt;
        ///  
        ///  &lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.1/jquery.min.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/jstree.m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlToHtml {
            get {
                return ResourceManager.GetString("XmlToHtml", resourceCulture);
            }
        }
    }
}
